### ISSUE TITLE
IT DUZNT WURK IN WINDOOOZZZZ XD :) ;P :) :) :)

### ISSUE THREAD

**Issue by KingLycosa** [hunter3035/PlexSort#1]
# WINDUMS IS BROKENZ 
**NGRRRP!P!!P!P! RECONCILE THIS PROBLEM MR HUNTER**

**Comment by hunter3035** [comment]
I believe I can work on an accommodation for WinCucks like yourself.

**Comment by hunter3035** [comment]
Fixed
